amg:
  adapter: "hci0"
  mac: "60:09:C3:1F:DC:1A"
  name: 'AMG_timer_DC1A'
  start_uuid: "6e400003-b5a3-f393-e0a9-e50e24dcca9e"
  write_uuid: "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
  # Optional initial commands to send right after connect
  init_cmds: []
  # Named command mappings for tools/amg_control.py and AmgClient helpers
  commands:
    beep:
      text: "BEEP"
    test_raw_aa10:
      hex: "AA-10"
sensors:
  - sensor: "Sensor_12E3"
    adapter: "hci0"
    mac: "F8:FE:92:31:12:E3"
    notify_uuid: "0000ffe4-0000-1000-8000-00805f9a34fb"
    config_uuid: "0000ffe9-0000-1000-8000-00805f9a34fb"
    idle_reconnect_sec: 300.0    # Longer idle timeout - 5 minutes
    keepalive_batt_sec: 30.0     # More frequent keepalive - 30 seconds
    reconnect_initial_sec: 0.1   # IMMEDIATE reconnect - within BT50 advertising window
    reconnect_max_sec: 2.0       # Max 2 seconds - must connect during advertising
detector:
  triggerHigh: 0.05   # Very low threshold - any movement triggers
  triggerLow: 0.01    # Minimal threshold for release
  ring_min_ms: 10     # Shorter minimum detection time
  dead_time_ms: 50    # Shorter dead time between hits
  warmup_ms: 2000     # Extended warmup for power state transitions
  baseline_min: 1e-6  # Very low baseline minimum
  min_amp: 0.01       # Critical: allow very small amplitudes
logging:
  dir: "./logs"
  file_prefix: "bridge"
  # Logging mode: 'verbose' will emit ALL debug events to normal logs location
  mode: "verbose"
  # Dual logging: create both normal and debug logs
  dual_file: true
  debug_subdir: "debug"
  # List debug msg names to allow in regular mode. Since we're in verbose mode, this is ignored.
  verbose_whitelist:
    - "Shot_raw"
    - "bt50_buffer_status"
    - "bt50_frame_raw"
    - "bt50_connection"
    - "amg_response"
    - "detector_state"